### ISSUE TITLE
 Request to Upload Jumpcutter Script on Google Drive or Mega

### ISSUE THREAD

**Issue by fartoot** [HaujetZhao/JumpCutter2#2]
As much as I'd love to try out the script, I noticed that the program is currently only available for download via 189.cn, which is unfortunately inaccessible from outside China. Many enthusiasts like me, who live outside China, are eager to use your script but are facing difficulties due to this limitation.

Would it be possible for you to consider uploading the "jumpcutter" script to a more accessible platform, such as Google Drive or Mega or dropbox or mediafire? By doing so, you would enable users from all around the world to benefit from your fantastic creation.

**Comment by HaujetZhao** [comment]
This project is far outdated, so not about to do so (for I'm temporarily nudbusy on a exam preparation). The newer method is to transcribe subtitles and edit the video by editing subtitles, the transcription can be done with whisper. 

Go check out https://github.com/mli/autocut

**Comment by HaujetZhao** [comment]
Also, this sctiptis written in python, you can run it directly with dependencies installed. The zip package in cloud storage is just a convenient way for users in China that don't have qualified internet to download spleeter model.

**Comment by fartoot** [comment]
Thanks for your comment and letting me know about the newer method. I appreciate your help!
Wishing you the best in your exams
